// demo-vue/src/components/layout/Header.vue
<template><header class="header-fixed">
  <h1>LOGO</h1>
  <a href="#" class="user-link" @click.prevent="toggleLogin">
    {{ user.isLoggedIn ? 'logout' : 'login' }}
  </a>
</header>

</template>
<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useUserStore } from '@/store/user'

const router = useRouter()
const user = useUserStore()

function toggleLogin() {
  if (user.isLoggedIn) {
    alert('초기화면으로 이동합니다.')
    user.logout()
    router.replace('/')
  } else {
    user.toggle()
  }
}
</script>

// demo-react/src/components/Header.tsx
import { useAuth } from '@/context/AuthContext'

export default function Header() {
    const { isLoggedIn, login, logout } = useAuth();

    const handleClick = (e: React.MouseEvent) => {
        e.preventDefault();
        if (isLoggedIn) {
            alert('로그아웃되었습니다.')
            logout()
        } else {
            alert('로그인되었습니다.')
            login()
        }
    }

    return (
        <header className="header-fixed">
            <h1>LOGO</h1>
            <button className="user-link" onClick={handleClick}>
                {isLoggedIn ? 'logout' : 'Login'}
            </button>
        </header>
    )
}
