// demo-vue/src/components/layout/Header.vue
<template><header class="header-fixed">
  <h1>LOGO</h1>
  <a href="#" class="user-link" @click.prevent="toggleLogin">
    {{ user.isLoggedIn ? 'logout' : 'login' }}
  </a>
</header>

</template>
<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useUserStore } from '@/store/user'

const router = useRouter()
const user = useUserStore()

function toggleLogin() {
  if (user.isLoggedIn) {
    alert('초기화면으로 이동합니다.')
    user.logout()
    router.replace('/')
  } else {
    user.toggle()
  }
}
</script>

// demo-next/src/component/common/Header.tsx
"use client"

import Link from "next/link"
import { useRouter } from "next/navigation"
import { useAuth } from "@/context/AuthContext"

import styles from "./Header.module.scss"

export default function Header() {
    const { isLoggedIn, login, logout } = useAuth()
    const router = useRouter()

    const handleClick = () => {
        if (isLoggedIn) {
            logout()
            alert("로그아웃 되었습니다. Home으로 이동합니다.")
            router.replace("/")
        } else {
            login()
            alert("로그인 되었습니다.")
        }
    }
    return (
        <header className={styles.headerFixed}>
            <h1>Next.js Demo</h1>
            <button className={styles.userLink} onClick={handleClick}>{isLoggedIn ? "Logout" : "Login"}</button>
        </header>
    )
}
